include:
  - project: 'platform/pipelines-templates'
    file: '/build/golang/template-app-go.yml'
    ref: master

default:
  image: golang:1.16.10

variables:
  IMAGE_NAME: tools/kubectl

test:
  parallel:
    matrix:
      # k8s apiserver and etcd binaries for 1.18 are not available at the moment in the kubebuilder-envtest bucket
      - ENVTEST_K8S_VERSION: ['1.22', '1.21', '1.20', '1.19']
  script:
    - make test
