config-map:
  - name: "pippo"
    data:
      - from: "literal|file"
        file: ./path
        key: key
        value: value
      - from: literal
        key: key1
        value: value1
      - from: literal
        key: key2
        value: {{PIPPO}}

secrets:
  - name: "pippo"
    when: "always|once"
    tls:
      cert: path
      key: path
    docker:
      username: {{DOCKER_USERNAME}}
      password: {{DOCKER_USERNAME}}
      email: {{DOCKER_USERNAME}}
      server: {{DOCKER_USERNAME}}
    data:
      - from: "literal|file"
        file: ./path
        key: key
        value: {{MLP}}
